install:
  - set QTDIR=C:\Qt\5.7\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
build_script:
  - git submodule update --init --recursive
  - qmake neuronify.pro
  - nmake
  - cp %QTDIR%\qml\* release
  - cp %VS120COMNTOOLS%\..\..\VC\redist\x64\Microsoft.VC120.CRT\* release
  - windeployqt.exe -quick -quickwidgets -multimediaquick -multimedia -opengl -quickparticles -quickwidgets -qmldir . release
